port=9099
dbPath=../../../../keil-data/.data
dbArchPath=../../../../keil-data/.data-arch/
env=dev
primary=true

# batches
fixedBatchTime=3600
dailyQueueCleanupTime=02:30:00
dailyBatchTime=03:00:00
dailyEmtpyTrxLineCleanupTime=03:30:00
dailyTransactionSummaryTime=23:00:00
dailySequenceResetNames=
monthlyTrxArchivalTime=-1

# standby dbs, comma separated
queueSize=512
standbyDbUrls=
standbyDbPorts=